name: copperblue
description: my atomic fedora GNOME

base-image: ghcr.io/ublue-os/silverblue-nvidia
image-version: latest

modules:
  - type: files
    files:
      - usr: /usr

  - type: rpm-ostree
#    repos:
    install:
      - openssl
      - gnome-tweaks
      - podman-compose
      - distrobox
    remove:
#      - firefox
#      - firefox-langpacks
      - toolbox

  - type: default-flatpaks
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)"
      install:
        - org.mozilla.firefox
#      remove:

  - type: signing
