name: copperblue
description: my atomic fedora GNOME

base-image: ghcr.io/ublue-os/silverblue-nvidia
image-version: latest

modules:
  - type: files
    files:
      - usr: /usr

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-39/atim-starship-fedora-39.repo
    install:
      - openssl
      - gnome-tweaks
      - podman-compose
      - distrobox
      - starship
    remove:
#      - firefox
#      - firefox-langpacks
      - toolbox
      - nvtop

  - type: default-flatpaks
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)"
      install:
        - org.mozilla.firefox
#      remove:

  - type: signing
